# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    if: guthub.event.pull_request.merged == true
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        url: "http://54.159.30.140:8080/job/node_pro/build?token=remote"
        user: "girish_devops"
        token: "11a7064883f4008ea58886ee866e84404d"
        job: "node_pro"
